

# This workflow will install Python dependencies, run tests, lint with a single version of Python, and upload a coverage report to Codecov
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12.9"]
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov matplotlib
        python -m pip install -e .
      
    - name: Run tests with Codecov coverage report
      run: pytest --cov=src/DSM --cov-report=xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true
